account/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

    PasswordChangeView,
    PasswordChangeDoneView,
)

from account.views import (
    login_view,
    logout_view,
    register_view,
    account_verify_view,
    account_view,
    account_update_view,
    account_search_view,
    account_deactivate_view,
    account_delete_view
)


app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('account_verify/<uidb64>/<token>/',
         account_verify_view, name='account-verify'),

    path('account/<user_id>/', account_view, name='account'),
    path('account_update/', account_update_view, name='account-update'),
    path('account_search/', account_search_view, name='account-search'),
    path('account_deactivate/', account_deactivate_view, name='account-deactivate'),
    path('account_delete/', account_delete_view, name='account-delete'),


    path('password_reset/', PasswordResetView.as_view(
        template_name='account/password/password_reset.html',
        email_template_name='account/password/password_reset_email.html',
        success_url=reverse_lazy('account:password-reset-done')),
        name='password-reset'
    ),
    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='account/password/password_reset_done.html'),
        name='password-reset-done'
    ),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='account/password/password_reset_confirm.html',
        success_url=reverse_lazy('account:password-reset-complete')),
        name='password-reset-confirm'
    ),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='account/password/password_reset_complete.html'),
        name='password-reset-complete'
    ),

    path('password_change/', PasswordChangeView.as_view(
        template_name='account/password/password_change.html',
        success_url=reverse_lazy('account:password-change-done')),
        name='password-change'
    ),
    path('password_change_done/', PasswordChangeDoneView.as_view(
        template_name='account/password/password_change_done.html'),
        name='password-change-done'
    ),
]

note/urls.py
from django.urls import path

from note.views import note_delete_view, note_view, note_delete_view

app_name = 'note'

urlpatterns = [
    path('note/', note_view, name='note'),
    path('note/<note_id>/', note_view, name='note'),
    path('note_delete/<note_id>/', note_delete_view, name='note-delete'),
]

notes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from notes.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),

    path('', include('account.urls', namespace='account')),
    path('api/', include('account.api.urls', namespace='account_api')),

    path('', include('note.urls', namespace='note')),
    path('api/', include('note.api.urls', namespace='note_api')),
]

handler404 = 'notes.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <title>Notes</title>
</head>
<body>

    {% include 'snippets/navbar.html' %}

    <div class="d-flex flex-column py-2 px-4 mx-auto">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} my-1 mx-auto">
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}

        {% block message %}{% endblock message %}
    </div>
    
    <main>
        {% block content %}{% endblock content %}
        <div class="sidebar">
            <div class="content-section">
                <p class="m-0 pb-2 border-bottom">Themes</p>
                <div class="mt-2 p-0">
                    <button class="btn mx-1 theme-picker theme-picker-light"></button>
                    <button class="btn mx-1 theme-picker theme-picker-dark"></button>
                </div>
            </div>
            {% block sidebar_extension %}{% endblock sidebar_extension %}
        </div>
    </main>

    <script>
        function setTheme() {
            const theme = localStorage.getItem("theme-mode")
            if (theme !== null) {
                if (theme === 'dark') {
                    document.getElementById("toggle-theme").innerText = "Light Mode"
                    document.body.setAttribute('data-theme', 'dark')
                }
            }
        }
        setTheme()

        document.getElementsByClassName('theme-picker-light')[0].addEventListener('click', () => {
            localStorage.removeItem("theme-mode")
            window.location.reload()
        })

        document.getElementsByClassName('theme-picker-dark')[0].addEventListener('click', () => {
            localStorage.setItem("theme-mode", "dark")
            window.location.reload() 
        })
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load temptags %}

{% block content %}
<div class="content-section my-auto">
    {% if request.user.is_authenticated %}
    <div class="d-flex my-2 pb-2 border-bottom">
        <a class="btn btn-outline-info mx-2" href="{% url 'note:note' %}">Add Note</a>
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="noteQuery" placeholder="Search Note">
        </form>
    </div>
    {% if notes %}
    <a href="{% url 'home' %}">
        <h3 class="my-4 pb-1 border-bottom">Notes</h3>
    </a>
    {% for note in notes %}
    <div class="border shadow-sm my-2 rounded">
        <a class="my-1" href="{% url 'note:note' note_id=note.id %}">
            <p class="m-2">{{ note.title }}</p>
        </a>
        <a class="my-1" href="{% url 'note:note' note_id=note.id %}">
            <p class="m-2">{{ note.body|bodySlice }}</p>
        </a>
    </div>
    {% endfor %}
    {% else %}
    <p class="my-0">Seems like you do not have any note. Try creating one. <a href="{% url 'note:note' %}"><strong>Add Note</strong></a></p>
    {% endif %}

    {% else %}
    <p class="my-0">Try creating your account if you are new here. <a href="{% url 'account:register' %}"><strong>Register</strong></a></p>
    <p class="my-0">If you already have an account. Login to view your notes. <a href="{% url 'account:login' %}"><strong>Login</strong></a></p>
    {% endif %}

</div>
{% endblock content %}